config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls', namespace='menu')),
]

menu/urls.py
from menu.apps import MenuConfig
from django.urls import path
from menu.views import MenuDetailView


app_name = MenuConfig.name


urlpatterns = [
    path('menu/<slug:name>/', MenuDetailView.as_view(), name='menu'),
]

menu/models.py
from django.db import models

# Create your models here.


NULLABLE = {'blank': True, 'null': True}


class Menu(models.Model):
    name = models.CharField(max_length=100, verbose_name='Вкладка меню')
    previous_tab = models.ForeignKey('self', **NULLABLE, verbose_name='предыдущая вкладка', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

menu/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView

from menu.models import Menu


# Create your views here.


class MenuDetailView(DetailView):
    model = Menu

    def get_object(self, queryset=None):
        name = self.kwargs.get('name')
        return get_object_or_404(Menu, name=name)

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        current_menu = context['object']

        ancestors = self.get_ancestors(current_menu)
        context['ancestors'] = ancestors

        descendants = self.get_descendants(current_menu)
        context['descendants'] = descendants

        return context

    @staticmethod
    def get_ancestors(menu):
        ancestors = []

        while menu.previous_tab:
            ancestors.insert(0, menu.previous_tab)
            menu = menu.previous_tab

        return ancestors

    @staticmethod
    def get_descendants(menu):
        return list(Menu.objects.filter(previous_tab=menu))

menu/templates/menu/menu_detail.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Offcanvas template for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/offcanvas/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/offcanvas.css' %}" rel="stylesheet">
  </head>

  <body class="bg-light">

    <nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Текущий путь:</a>
      <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          {% if ancestors %}
            {% for ancestor in ancestors %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'menu:menu' ancestor.name %}">{{ ancestor.name|title }}</a>
              </li>
            {% endfor %}
          {% endif %}
          <li class="nav-item active">
            <a class="nav-link" href="#">{{ object.name|title }}<span class="sr-only">(current)</span></a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="nav-scroller bg-white box-shadow">
      <nav class="nav nav-underline">
        <a class="nav-link active" href="#"></a>
        <a class="nav-link" href="#">

          <span class="badge badge-pill bg-light align-text-bottom">27</span>
        </a>
        <a class="nav-link" href="#">Explore</a>
        <a class="nav-link" href="#">Suggestions</a>
        <a class="nav-link" href="#">Link</a>
        <a class="nav-link" href="#">Link</a>
        <a class="nav-link" href="#">Link</a>
        <a class="nav-link" href="#">Link</a>
        <a class="nav-link" href="#">Link</a>
      </nav>
    </div>

    <main role="main" class="container">
      <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded box-shadow">
        <div class="lh-100">
          <h6 class="mb-0 text-white lh-100"></h6>
          <small></small>
        </div>
      </div>

      <div class="my-3 p-3 bg-white rounded box-shadow">
        <h6 class="border-bottom border-gray pb-2 mb-0">В этом меню:</h6>
        {% if descendants %}
          {% for descendant in descendants %}
            <div class="media text-muted pt-3">
              <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                <strong class="d-block text-gray-dark">{{ descendant.name }}</strong>
                <small class="d-block text-right mt-3">
                  <a href="{% url 'menu:menu' descendant.name %}">Перейти</a>
                </small>
              </p>
            </div>
          {% endfor %}
        {% endif %}
      </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="{% static 'js/vendor/jquery-slim.min.js' %}"><\/script>')</script>
    <script src="{% static 'js/vendor/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/vendor/holder.min.js' %}"></script>
    <script src="{% static 'offcanvas.js' %}"></script>
  </body>
</html>